name: Run Tests

on:
  pull_request:
    branches: [ main, dev ]  # main과 dev 브랜치에 대한 PR에 대해 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 사용하는 Node.js 버전에 맞게 수정

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    # (선택사항) 테스트 커버리지 보고
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
